# Generated by Django 2.1 on 2018-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0002_auto_20180814_0857")]

    operations = [
        migrations.AlterModelOptions(
            name="authtoken",
            options={"verbose_name": "AuthToken", "verbose_name_plural": "AuthTokens"},
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
                verbose_name="Key",
            ),
        ),
    ]
