# Generated by Django 2.0.7 on 2018-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blacklist", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="EmailEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("entry_value", models.EmailField(max_length=254)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="EmailHostEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("entry_value", models.CharField(max_length=254)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="IPEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("entry_value", models.GenericIPAddressField()),
            ],
            options={"abstract": False},
        ),
        migrations.DeleteModel(name="Email_Entry"),
        migrations.DeleteModel(name="Host_Entry"),
        migrations.DeleteModel(name="IP_Entry"),
    ]
