# Generated by Django 2.0.7 on 2018-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("blacklist", "0003_auto_20180725_1211"),
        ("blacklist", "0004_emailentry_lower_case_entry_value"),
        ("blacklist", "0005_remove_ipentry_lower_case_entry_value"),
        ("blacklist", "0006_ipentry_lower_case_entry_value"),
        ("blacklist", "0007_remove_ipentry_lower_case_entry_value"),
        ("blacklist", "0008_ipentry_lower_case_entry_value"),
        ("blacklist", "0009_remove_ipentry_lower_case_entry_value"),
        ("blacklist", "0010_ipentry_lower_case_entry_value"),
    ]

    dependencies = [
        (
            "blacklist",
            "0002_auto_20180725_1038_squashed_0004_emailhostentry_lower_case_entry_value",
        )
    ]

    operations = [
        migrations.RemoveField(model_name="emailentry", name="lower_case_entry_value"),
        migrations.AlterField(
            model_name="emailhostentry",
            name="lower_case_entry_value",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="emailentry",
            name="lower_case_entry_value",
            field=models.EmailField(
                default="a@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="ipentry", name="lower_case_entry_value"),
        migrations.AddField(
            model_name="ipentry",
            name="lower_case_entry_value",
            field=models.GenericIPAddressField(default="0.0.0.0", unique=True),
            preserve_default=False,
        ),
    ]
