# Generated by Django 2.0.7 on 2018-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blacklist",
            "0003_auto_20180725_1211_squashed_0010_ipentry_lower_case_entry_value",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="ipentry",
            name="lower_case_entry_value",
            field=models.GenericIPAddressField(null=True, unique=True),
        )
    ]
