# Generated by Django 2.0.7 on 2018-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blacklist", "0004_auto_20180726_0825")]

    operations = [
        migrations.AlterField(
            model_name="emailentry",
            name="lower_case_entry_value",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="emailhostentry",
            name="lower_case_entry_value",
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
